spring.datasource.url=jdbc:mysql://localhost:3306/electric_bill_db

spring.datasource.username=root

spring.datasource.password=danush19

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8081